num1 = int(input("Give me the first number: "))
num2 = int(input("Give me the secand number: "))
print("Thank you!")
print(str(num1) + " + " + str(num2) + " = " , end = "")
print(num1 + num2)
print(str(num1) + " - " + str(num2) + " = " , end = "")
print(num1 - num2)
print(str(num1) + " / " + str(num2) + " = " , end = "")
print(int(num1 / num2))
print(str(num1) + " * " + str(num2) + " = " , end = "")
print(num1 * num2)